version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=just_test
  app:
    image: books-crud
    ports:
      - 13000:8080